import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import { RouterProvider, createRouter } from '@tanstack/solid-router';
import { onSettled } from 'solid-js';
import './App.css';

// Generated by @tanstack/router-plugin from the files under src/routes —
// TanStack derives full typesafety for <Link>, params, and loader data
// from this tree.
import { routeTree } from './routeTree.gen';

import { applyTheme, watchSystemTheme } from './lib/theme';

const router = createRouter({
  routeTree,
  // Mount the whole router at a sub-path so every route lives under
  // /panel-admin/*. Incoming paths outside this basepath are rewritten by
  // the router; the bare root is redirected to the basepath (see onSettled).
  basepath: '/panel-admin',
  defaultPendingComponent: () => <main>Loading…</main>,
});

// Registers the router's types library-wide, so `to`/`params` on every
// <Link> typecheck against the actual routes.
declare module '@tanstack/solid-router' {
  interface Register {
    router: typeof router;
  }
}

const queryClient = new QueryClient();

// The app root: the plugin's generated entries render this component,
// wrapped in src/Document.tsx. QueryClientProvider wraps the router so the
// data hooks (useUsers, useAuth, …) work anywhere in the tree.
export default function App() {
  onSettled(() => {
    applyTheme();
    watchSystemTheme();
    // Auto-redirect the bare root to the router basepath so `/` lands on
    // the app instead of a 404.
    if (typeof window !== 'undefined') {
      const path = window.location.pathname;
      if (path === '/' || path === '') {
        window.location.replace('/panel-admin');
      }
    }
  });

  return (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  );
}
