import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import { RouterProvider, createRouter } from '@tanstack/solid-router';
import './App.css';

// Generated by @tanstack/router-plugin from the files under src/routes —
// TanStack derives full typesafety for <Link>, params, and loader data
// from this tree.
import { routeTree } from './routeTree.gen';

const router = createRouter({
  routeTree,
  defaultPendingComponent: () => <main>Loading…</main>,
});

// Registers the router's types library-wide, so `to`/`params` on every
// <Link> typecheck against the actual routes.
declare module '@tanstack/solid-router' {
  interface Register {
    router: typeof router;
  }
}

const queryClient = new QueryClient();

// The app root: the plugin's generated entries render this component,
// wrapped in src/Document.tsx. QueryClientProvider wraps the router so the
// data hooks (useUsers, useAuth, …) work anywhere in the tree.
export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  );
}
