/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelAdminRouteImport } from './routes/panel-admin'
import { Route as PanelAdminIndexRouteImport } from './routes/panel-admin/index'
import { Route as PanelAdminAnalyticsRouteImport } from './routes/panel-admin/analytics'
import { Route as PanelAdminOrdersRouteImport } from './routes/panel-admin/orders'
import { Route as PanelAdminSettingsRouteImport } from './routes/panel-admin/settings'
import { Route as PanelAdminUsersRouteImport } from './routes/panel-admin/users'
import { Route as PanelAdminOrdersCompletedRouteImport } from './routes/panel-admin/orders/completed'
import { Route as PanelAdminOrdersPendingRouteImport } from './routes/panel-admin/orders/pending'
import { Route as PanelAdminUsersIdRouteImport } from './routes/panel-admin/users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/panel-admin',
  path: '/panel-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdminIndexRoute = PanelAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminAnalyticsRoute = PanelAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminOrdersRoute = PanelAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminSettingsRoute = PanelAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminUsersRoute = PanelAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminOrdersCompletedRoute =
  PanelAdminOrdersCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => PanelAdminOrdersRoute,
  } as any)
const PanelAdminOrdersPendingRoute = PanelAdminOrdersPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => PanelAdminOrdersRoute,
} as any)
const PanelAdminUsersIdRoute = PanelAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panel-admin': typeof PanelAdminRouteWithChildren
  '/panel-admin/analytics': typeof PanelAdminAnalyticsRoute
  '/panel-admin/orders': typeof PanelAdminOrdersRouteWithChildren
  '/panel-admin/settings': typeof PanelAdminSettingsRoute
  '/panel-admin/users': typeof PanelAdminUsersRouteWithChildren
  '/panel-admin/': typeof PanelAdminIndexRoute
  '/panel-admin/orders/completed': typeof PanelAdminOrdersCompletedRoute
  '/panel-admin/orders/pending': typeof PanelAdminOrdersPendingRoute
  '/panel-admin/users/$id': typeof PanelAdminUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panel-admin/analytics': typeof PanelAdminAnalyticsRoute
  '/panel-admin/orders': typeof PanelAdminOrdersRouteWithChildren
  '/panel-admin/settings': typeof PanelAdminSettingsRoute
  '/panel-admin/users': typeof PanelAdminUsersRouteWithChildren
  '/panel-admin': typeof PanelAdminIndexRoute
  '/panel-admin/orders/completed': typeof PanelAdminOrdersCompletedRoute
  '/panel-admin/orders/pending': typeof PanelAdminOrdersPendingRoute
  '/panel-admin/users/$id': typeof PanelAdminUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panel-admin': typeof PanelAdminRouteWithChildren
  '/panel-admin/analytics': typeof PanelAdminAnalyticsRoute
  '/panel-admin/orders': typeof PanelAdminOrdersRouteWithChildren
  '/panel-admin/settings': typeof PanelAdminSettingsRoute
  '/panel-admin/users': typeof PanelAdminUsersRouteWithChildren
  '/panel-admin/': typeof PanelAdminIndexRoute
  '/panel-admin/orders/completed': typeof PanelAdminOrdersCompletedRoute
  '/panel-admin/orders/pending': typeof PanelAdminOrdersPendingRoute
  '/panel-admin/users/$id': typeof PanelAdminUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel-admin'
    | '/panel-admin/analytics'
    | '/panel-admin/orders'
    | '/panel-admin/settings'
    | '/panel-admin/users'
    | '/panel-admin/'
    | '/panel-admin/orders/completed'
    | '/panel-admin/orders/pending'
    | '/panel-admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/panel-admin/analytics'
    | '/panel-admin/orders'
    | '/panel-admin/settings'
    | '/panel-admin/users'
    | '/panel-admin'
    | '/panel-admin/orders/completed'
    | '/panel-admin/orders/pending'
    | '/panel-admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/panel-admin'
    | '/panel-admin/analytics'
    | '/panel-admin/orders'
    | '/panel-admin/settings'
    | '/panel-admin/users'
    | '/panel-admin/'
    | '/panel-admin/orders/completed'
    | '/panel-admin/orders/pending'
    | '/panel-admin/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelAdminRoute: typeof PanelAdminRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-admin': {
      id: '/panel-admin'
      path: '/panel-admin'
      fullPath: '/panel-admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-admin/': {
      id: '/panel-admin/'
      path: '/'
      fullPath: '/panel-admin/'
      preLoaderRoute: typeof PanelAdminIndexRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel-admin/analytics': {
      id: '/panel-admin/analytics'
      path: '/analytics'
      fullPath: '/panel-admin/analytics'
      preLoaderRoute: typeof PanelAdminAnalyticsRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel-admin/orders': {
      id: '/panel-admin/orders'
      path: '/orders'
      fullPath: '/panel-admin/orders'
      preLoaderRoute: typeof PanelAdminOrdersRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel-admin/settings': {
      id: '/panel-admin/settings'
      path: '/settings'
      fullPath: '/panel-admin/settings'
      preLoaderRoute: typeof PanelAdminSettingsRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel-admin/users': {
      id: '/panel-admin/users'
      path: '/users'
      fullPath: '/panel-admin/users'
      preLoaderRoute: typeof PanelAdminUsersRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel-admin/orders/completed': {
      id: '/panel-admin/orders/completed'
      path: '/completed'
      fullPath: '/panel-admin/orders/completed'
      preLoaderRoute: typeof PanelAdminOrdersCompletedRouteImport
      parentRoute: typeof PanelAdminOrdersRoute
    }
    '/panel-admin/orders/pending': {
      id: '/panel-admin/orders/pending'
      path: '/pending'
      fullPath: '/panel-admin/orders/pending'
      preLoaderRoute: typeof PanelAdminOrdersPendingRouteImport
      parentRoute: typeof PanelAdminOrdersRoute
    }
    '/panel-admin/users/$id': {
      id: '/panel-admin/users/$id'
      path: '/$id'
      fullPath: '/panel-admin/users/$id'
      preLoaderRoute: typeof PanelAdminUsersIdRouteImport
      parentRoute: typeof PanelAdminUsersRoute
    }
  }
}

interface PanelAdminOrdersRouteChildren {
  PanelAdminOrdersCompletedRoute: typeof PanelAdminOrdersCompletedRoute
  PanelAdminOrdersPendingRoute: typeof PanelAdminOrdersPendingRoute
}

const PanelAdminOrdersRouteChildren: PanelAdminOrdersRouteChildren = {
  PanelAdminOrdersCompletedRoute: PanelAdminOrdersCompletedRoute,
  PanelAdminOrdersPendingRoute: PanelAdminOrdersPendingRoute,
}

const PanelAdminOrdersRouteWithChildren =
  PanelAdminOrdersRoute._addFileChildren(PanelAdminOrdersRouteChildren)

interface PanelAdminUsersRouteChildren {
  PanelAdminUsersIdRoute: typeof PanelAdminUsersIdRoute
}

const PanelAdminUsersRouteChildren: PanelAdminUsersRouteChildren = {
  PanelAdminUsersIdRoute: PanelAdminUsersIdRoute,
}

const PanelAdminUsersRouteWithChildren = PanelAdminUsersRoute._addFileChildren(
  PanelAdminUsersRouteChildren,
)

interface PanelAdminRouteChildren {
  PanelAdminAnalyticsRoute: typeof PanelAdminAnalyticsRoute
  PanelAdminOrdersRoute: typeof PanelAdminOrdersRouteWithChildren
  PanelAdminSettingsRoute: typeof PanelAdminSettingsRoute
  PanelAdminUsersRoute: typeof PanelAdminUsersRouteWithChildren
  PanelAdminIndexRoute: typeof PanelAdminIndexRoute
}

const PanelAdminRouteChildren: PanelAdminRouteChildren = {
  PanelAdminAnalyticsRoute: PanelAdminAnalyticsRoute,
  PanelAdminOrdersRoute: PanelAdminOrdersRouteWithChildren,
  PanelAdminSettingsRoute: PanelAdminSettingsRoute,
  PanelAdminUsersRoute: PanelAdminUsersRouteWithChildren,
  PanelAdminIndexRoute: PanelAdminIndexRoute,
}

const PanelAdminRouteWithChildren = PanelAdminRoute._addFileChildren(
  PanelAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelAdminRoute: PanelAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
